//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressPractice.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using AddressPractice.Extensions;


    public partial class ADDRESS_MASTER
    {
        
        public int? id { get; set; }

        [Display(Name = "名前")]
        [Required(ErrorMessage ="氏名は必須項目です")]
        [String(ErrorMessage = "文字数オーバーです")]
        public string name { get; set; }
        
        [Blackword("違法,麻薬,毒")]
        [Display(Name = "名前（フリガナ）")]
        public string furigana { get; set; }
        
        [Display(Name = "性別")]
        public string gender { get; set; }
        
        [Display(Name = "血液型")]
        public string bloodType { get; set; }
        
        [Display(Name = "誕生日")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> birthDay { get; set; }
        
        [Display(Name = "電話番号")]
        public string homePhone { get; set; }
        
        [Display(Name = "携帯電話番号")]
        [Phone(ErrorMessage = "電話番号の形式で入力してください")]
        public string cellPhone { get; set; }
        
        [EmailAddress]
        [Display(Name = "メールアドレス")]
        public string mailAddress { get; set; }
        
        [Display(Name = "郵便番号")]
        public string postalCode { get; set; }
        
        [Display(Name = "住所")]
        public string homeAddress { get; set; }
        
        [Display(Name = "住所（フリガナ）")]
        public string homeFurigana { get; set; }
        
        [DataType(DataType.Date)]
        [NotMapped]
        public Nullable<System.DateTime> fromBirthDay { get; set; }
        
        [DataType(DataType.Date)]
        [NotMapped]
        public Nullable<System.DateTime> toBirthDay { get; set; }
    }
}
